services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      cap_add: "SYS_NICE"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: drupaldb
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  database: